config/routes.rb
Roland808::Application.routes.draw do
  root :to => 'kits#index'
  resources :samplers, :kits, :instruments
end

app/models/instrument.rb
# == Schema Information
#
# Table name: instruments
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  sound      :string(255)
#  pic        :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Instrument < ActiveRecord::Base
  attr_accessible :name, :sound, :pic, :kit_id
  has_and_belongs_to_many :kits
end

app/models/kit.rb
# == Schema Information
#
# Table name: kits
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  pic        :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  sampler_id :integer
#

class Kit < ActiveRecord::Base
  attr_accessible :name, :pic, :sampler_id
  belongs_to :sampler
  has_and_belongs_to_many :instruments
end

app/models/sampler.rb
# == Schema Information
#
# Table name: samplers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  pic        :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Sampler < ActiveRecord::Base
  attr_accessible :name, :pic
  has_many :kits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  def index
    @instruments = Instrument.all
  end

  def create
    instrument = Instrument.create(params[:instrument])
    redirect_to(instruments_path)
  end

  def new
    @instrument = Instrument.new
  end

  def edit
    @instrument = Instrument.find(params[:id])
    render 'edit'
  end

  def show
    @instrument = Instrument.find(params[:id])
  end

  def update
    instrument = Instrument.find(params[:id])
    instrument.update_attributes(params[:instrument])
    redirect_to(instruments_path)
  end

  def destroy
    instrument = Instrument.find(params[:id])
    instrument.delete
    redirect_to(instruments_path)
  end
end

app/controllers/kits_controller.rb
class KitsController < ApplicationController
  def index
    @kits = Kit.all
  end

  def create
    kit = Kit.create(params[:kit])
    redirect_to(kit)
  end

  def new
    @kit = Kit.new
  end

  def edit
    @kit = Kit.find(params[:id])
    render 'new'
  end

  def show
    @kit = Kit.find(params[:id])
  end

  def update
    kit = Kit.find(params[:id])
    kit.update_attributes(params[:kit])
    redirect_to(kits_path)
  end

  def destroy
    kit = Kit.find(params[:id])
    kit.delete
    redirect_to(kits_path)
  end
end

app/controllers/samplers_controller.rb
class SamplersController < ApplicationController
  def index
    @samplers = Sampler.all
  end

  def create
    sampler = Sampler.create(params[:sampler])
    redirect_to(samplers_path)
  end

  def new
    @sampler = Sampler.new
  end

  def edit
    @sampler = Sampler.find(params[:id])
    render 'new'
  end

  def show
    @sampler = Sampler.find(params[:id])
  end

  def update
    sampler = Sampler.find(params[:id])
    sampler.update_attributes(params[:sampler])
    redirect_to(samplers_path)
  end

  def destroy
    sampler = Sampler.find(params[:id])
    sampler.delete
    redirect_to(samplers_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/instruments/_form.html.erb
<%= form_for @instrument do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :pic %>
  <%= f.text_field :pic %>
  <br>
  <%= f.label :sound %>
  <%= f.text_field :sound %>
  <br>
  <%= f.label :kit_id %>
<%= f.select :kit_id, Kit.all.map{|kit| [kit.name, kit.id]} %>
<br>
  <%= f.submit %>
<% end %>

app/views/instruments/edit.html.erb
<%= render :partial => 'form' %>

app/views/instruments/index.html.erb
<% @instruments.each do |instrument| %>
<br>
<%= link_to(instrument.name, instrument) %>


 <ul id="<%=instrument.id%>" class="nav">
       <li>
        <a href="#">Home</a>
        <audio id="beep-one" preload="auto">
        <source src="<%= instrument.sound %>"></source>
        <source src="audio/beep.ogg"></source>
        Your browser isn't invited for super fun time.
      </audio>
      </li>
    </ul>

    <script>
    var beepOne = $("#<%= instrument.id %>")[0];
    $("#<%=instrument.id%>")
    .mouseenter(function() {
    beepOne.play();
    });
    </script>

<br>
<%= link_to 'Delete', instrument, :method => :delete, :confirm => 'Okay to delete?' %>
<br>
<%= link_to 'Edit', edit_instrument_path(instrument) %>
<br>
<% end %>

app/views/instruments/new.html.erb
<%= render :partial => 'form' %>

app/views/instruments/show.html.erb
<ul id="nav-three" id="soundid">
<p class="blip">
<%= image_tag(@instrument.pic) %>
</p>
        <audio id="beep-three" preload="auto">
        <source src='<%= @instrument.sound %>'></source>
        Your browser isn't invited for super fun time.
      </audio>
    <script>$("p.blip")
  .each(function(i) {
    if (i >= 0) {
      $("#beep-three")
        .attr("id", "beep-three" + i)
        .appendTo($(this).parent());
    }
    $(this).data("beeper", i);
  })
  .mouseenter(function() {
    $("#beep-three" + $(this).data("beeper"))[0].play();
  });
$("#beep-three").attr("id", "beep-three");</script>
<%= link_to 'Delete', @instrument, :method => :delete, :confirm => 'Okay to delete?' %>
<%= link_to 'Edit', edit_instrument_path(@instrument) %>
</ul>

app/views/kits/_form.html.erb
<%= form_for @kit do |f| %>
<table>
<tr><td>
  <%= f.label :name, "title" %>
</td><td>
  <%= f.text_field :name %><br>
  </td>
  </tr>
  <tr><br>
  </tr>
  <tr>
    <td>
    <%= f.label :pic, "url" %>
</td>
<td>
  <%= f.text_field :pic %>
  </td>
  </tr>
  <tr><br>
  </tr>
  <tr>
    <td>
  <%= f.label :sampler_id, "category" %></td>
  <td>
<%= f.select :sampler_id, Sampler.all.map{|sampler| [sampler.name, sampler.id]} %>
  </td>
  </tr>
  <tr><br>
  </tr>
<tr>
<td>
</td>
<td>
  <%= f.submit "Add" %>
</td>
</tr>
</table>
<% end %>

app/views/kits/edit.html.erb
<div id="chasm">
<%= render :partial => 'form' %>
</dv>

app/views/kits/index.html.erb
<% @kits.each do |kit| %>
<div id="gif">
      <img src="<%= kit.pic %>" width = '200' height = '200'>

    <div id="bottominfo">
    <div id="title">
           <%= link_to(kit.name, kit) %>
         </div>
         <div id="deledit">
<%= link_to 'Delete', kit, :method => :delete, :confirm => 'Okay to delete?' %>
<%= link_to 'Edit', edit_kit_path(kit) %>
</div>
</div>
   </div>
<% end %>

app/views/kits/new.html.erb
<div id="chasm">
<%= render :partial => 'form' %>
</div>

app/views/kits/show.html.erb
<!-- <div id="show"> -->
<%= image_tag(@kit.pic, :height => '500px') %>
<br>
<%= @kit.name %>
<br>
<br>
<%= link_to 'Delete', @kit, :method => :delete, :confirm => 'Okay to delete?' %>
<%= link_to 'Edit', edit_kit_path(@kit) %>
<br>
<!-- </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GifUnion</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<img src="http://i.imgur.com/XsBDefn.png">
<nav>
<%= link_to('all gifs', kits_path) %> /
<%= link_to('categories', samplers_path) %> /
<%= link_to('new gif', new_kit_path) %>
</nav>
<body>
<%= yield %>
</body>
</html>

app/views/samplers/_form.html.erb
<%= form_for @sampler do |f| %>
  <%= f.label :name, "category" %>
  <%= f.text_field :name %><br>
    <%= f.label :pic, "image url" %>
  <%= f.text_field :pic %>
  <br>
  <%= f.submit %>
<% end %>

app/views/samplers/edit.html.erb
<%= render :partial => 'form' %>

app/views/samplers/index.html.erb
<div id="chasm">
<% @samplers.each do |sampler| %>
<div id="cat">
<div id="cattitle">
   <img src="<%= sampler.pic %>" width = '200' height = '200'>
</div>
<div id="title">
<%= link_to(sampler.name, sampler) %>
</div>

</div>
<% end %>
</div>

app/views/samplers/new.html.erb
<%= render :partial => 'form' %>

app/views/samplers/show.html.erb
<div id="cat">


   <img src="<%= @sampler.pic %>" width = '200' height = '200'>
</div>
<% @sampler.kits.each do |kit| %>
<div id="gif">
    <img src="<%= kit.pic %>" width = '200' height = '200'>

<%= link_to(kit.name, kit) %>
<%= link_to 'delete', @sample, :method => :delete, :confirm => 'Okay to delete?' %>

</div>
<% end %>